### ISSUE TITLE
抽取中文完毕后，更新相关 TS 的定义

### ISSUE THREAD

**Issue by zhaoyangsoft** [nefe/kiwi-linter#2]
抽取变量后要更新相关缓存
 否则 IDE 里边会报错，

![image](https://user-images.githubusercontent.com/1456421/43830160-3e95f8b6-9b33-11e8-8835-858a884bbacd.png)

**Comment by linhuiw** [comment]
恩，文件自动抽取后，需要更新 ts 定义的缓存，这里我调研下相关机制。

感谢反馈。
